name: Update Version on PR Merge

on:
  pull_request:
    types: [closed]  # Trigger this workflow when a PR is closed (merged or just closed)

permissions:
  contents: write
  pull-requests: read  # Only read access is needed to fetch PR labels

jobs:
  update-version:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Ensure the full history is fetched

    - name: Get PR Labels
      id: get_labels
      run: |
        if [ "${{ github.event.pull_request.merged }}" != "true" ]; then
          echo "PR not merged. Exiting."
          exit 0
        fi
        
        PR_NUMBER=${{ github.event.pull_request.number }}
        echo "Fetching labels for PR #${PR_NUMBER}"
        
        # Fetch PR labels using GitHub API
        labels=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
                          "https://api.github.com/repos/${{ github.repository }}/issues/${PR_NUMBER}/labels" \
                          | jq -r '.[].name')
        
        echo "Labels: $labels"

        # Determine increment type based on labels
        if echo "$labels" | grep -q 'major'; then
          echo "INCREMENT=major" >> $GITHUB_ENV
        elif echo "$labels" | grep -q 'minor'; then
          echo "INCREMENT=minor" >> $GITHUB_ENV
        elif echo "$labels" | grep -q 'build'; then
          echo "INCREMENT=build" >> $GITHUB_ENV
        elif echo "$labels" | grep -q 'revision'; then
          echo "INCREMENT=revision" >> $GITHUB_ENV
        else
          echo "INCREMENT=" >> $GITHUB_ENV
        fi

    - name: Increment version
      id: increment_version
      run: |
        file="my-node-app/package.json"  # Path to your package.json file
        
        # Extract current version
        current_version=$(jq -r '.version' $file)
        echo "Current version: $current_version"

        # Define the function to increment the version
        increment_version() {
          local version=$1
          IFS='.' read -r major minor patch <<< "$version"

          case $INCREMENT in
            major)
              major=$((major + 1))
              minor=0
              patch=0
              ;;
            minor)
              minor=$((minor + 1))
              patch=0
              ;;
            build)
              patch=$((patch + 1))
              ;;
            revision)
              patch=$((patch + 1))
              ;;
            *)
              echo "No increment specified. Skipping version update."
              exit 0
              ;;
          esac

          echo "$major.$minor.$patch"
        }

        # Check for the increment type
        if [ -z "$INCREMENT" ]; then
          echo "No increment type specified. Exiting."
          exit 0
        fi

        # Calculate new version
        new_version=$(increment_version "$current_version")
        echo "Updating version from $current_version to $new_version"

        # Update version in package.json
        jq --arg new_version "$new_version" '.version = $new_version' $file > temp.json && mv temp.json $file

        # Debug: Print the file content after modification
        echo "Modified file content:"
        cat $file

        # Output the new version so it can be used in later steps
        echo "new_version=$new_version" >> $GITHUB_ENV
    - name: Install dependencies
      run: npm install
      working-directory: ./my-node-app
      
    - name: List directory contents
      run: ls -R

    - name: ANother update
      run: npm version minor
      working-directory: ./my-node-app
      
    - name: Commit and push changes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config user.name "ahtesham-haq"
        git config user.email "ahtesham.ul.haq@healthwaresystems.com"
        
        # Check if there are changes to commit
        if [ -n "$(git status --porcelain)" ]; then
          # Add and commit changes
          git add .
          git diff --cached --name-only  # Check what files are staged
          git commit -m "Incremented version to ${{ env.new_version }}"
          
          # Push changes to main branch
          git push origin main
        else
          echo "No changes to commit."
        fi
